version: 0.1 
 
phases: 
  install: 
    commands: 
      # Upgrade PIP 
      # - pip install --upgrade pip 
 
      # Upgrade AWS CLI to the latest version 
      - pip install --upgrade awscli 
 
      # Ensure latest npm (hopefully) 
      - npm i npm@latest -g 
 
      # Install dependencies needed for running tests 
      - npm install 
  pre_build: 
    commands: 
      # Placeholder 
  post_build: 
    commands: 
      # Placeholder 
  build: 
    commands: 
      - npm run build 
artifacts: 
  type: zip 
  files: 
    - '**/*' 
  base-directory: 'build' 